# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-06 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
